#役はなく細かい加点で点数を稼ぐハグルです。役をあまり意識せず手札を７枚持ってたプレイヤーが勝ったので、手札上限をもうけたほうがよかったかな？と反省しています。 2017/04/28 作者: @__YamYuki__
num_players = 6
players = ['yama', 'pa', 'pb', 'pc', 'pd', 'pe', ]
token_type = 'card'
num_rules = 17
rules = [
    'ダイアの8のカードをもっていると8点を得る。',
    'スートがすべてスペードあるいはスートがすべてクラブなら10点を得る。',
    'スートがすべて赤いと-10点を得る。',
    'Jをちょうど２枚ずつもっていたら11点を得る。',
    'QとKを１枚ずつのみもっていてそれらのスートの色が同じなら5点を得る。',
]
rule_assign = [
    [1, 10, 16, ],
    [2, 7, 12, ],
    [3, 11, 13, ],
    [5, 8, 17, ],
    [6, 14, ],
]
card_assign = [
    ['d7', 'c8', 'h9', 's11', 'c12', ],
    ['s8', 'd9', 'd11', 'h12', 'c13', ],
    ['s9', 'c10', 'd10', 'h11', 'h1', ],
    ['d8', 'h8', 'c9', 's12', 'h13', ],
    ['h7', 's10', 'c11', 'd13', 'j0', ],
    ['s7', 'c7', 'h10', 'd12', 's13', 's1', ],
]
