#役はなく細かい加点で点数を稼ぐハグルです。役をあまり意識せず手札を７枚持ってたプレイヤーが勝ったので、手札上限をもうけたほうがよかったかな？と反省しています。 2017/04/28 作者: @__YamYuki__
num_players = 6
players = ["yama", "pa", "pb", "pc", "pd", "pe", ]
token_type = "card"
num_rules = 17
rules = [
    "ダイアの8のカードをもっていると8点を得る。",
    "スートがすべてスペードあるいはスートがすべてクラブなら10点を得る。",
    "スートがすべて赤いと-10点を得る。",
    "Jをちょうど２枚ずつもっていたら11点を得る。",
    "QとKを１枚ずつのみもっていてそれらのスートの色が同じなら5点を得る。",
    "8,9,10のカードを1枚ずつのみもっていてそれらのスートが異なるなら15点を得る。",
    "7のカードをちょうど3枚持っていると7点を得る。",
    "9のカードをちょうど4枚もっていると10点を得る。",
    "同じ数のカード2枚と別に同じ数のカード3枚のちょうど5枚のカードをもっている、いわゆるフルハウスだと10点を得る。手札が6枚以上の時は無効。",
    "絵札(J,Q,K,A)を3枚,4枚,5枚,6枚以上もっているとそれぞれ-5,-15,-10,-20点を得る。例えば、ゲーム終了時手札が7,J,J,Q,Kなら-10点を得る。",
    "JOKERはいわゆるワイルドカードとしてあつかうこと(好きな数字、好きなスートとみなすこと)ができる。他のルールではJOKERに関する記載がない時は、完全にそのカードとして扱う。ルールごとに好きカードとしてあつかうことはできない。",
    "JOKERを持っていると-15点を得る。",
    "ハートのAのカードをもっているとルール12を無効にできる。",
    "全ての手札のカードの数字を足した点数を得る。J,Q,K,Aはそれぞれ11,12,13,14として扱う。例えば、ゲーム終了時手札が7,8,10,J,Aなら50点を得る。",
    "今回のゲームで使われているカードの数字は7,8,9,10,J,Q,K,Aであり、スートはスペード、ハート、クラブ、ダイヤである。ただし、クラブとダイヤのAはない。これにJOKER1枚を含めた計31枚が使われている。",
    "ルールは全部で17個ありカードは31枚使われている。ルールは1人に2個または3個配られ、カードはルールが2個配られた人には6枚、3個配られた人には5枚配られている。",
    "ロビーでゲームマスターに残り時間10分前までに残り時間を聞くと5点を得る。残り時間10分を切った後に残り時間を聞くと-5点を得る。",
]
rule_assign = [
    [1, 10, 16, ],
    [2, 7, 12, ],
    [3, 11, 13, ],
    [5, 8, 17, ],
    [6, 14, ],
]
card_assign = [
    ["d7", "c8", "h9", "s11", "c12", ],
    ["s8", "d9", "d11", "h12", "c13", ],
    ["s9", "c10", "d10", "h11", "h1", ],
    ["d8", "h8", "c9", "s12", "h13", ],
    ["h7", "s10", "c11", "d13", "j0", ],
    ["s7", "c7", "h10", "d12", "s13", "s1", ],
]
